version: '3.8'
services: 
  my-app:
    image: 015963245704.dkr.ecr.us-east-1.amazonaws.com/my-app:1.0
    ports: 
      - 3000:3000
  mongodb:
    image: mongo
    ports: 
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin  
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports: 
      - 8081:8081
    restart: always
    depends_on: 
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin 
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local
